name: CI/CD for Wisecow

on:
  push:
    branches: [ main ]

env:
  IMAGE: harsha12101503/wisecow

jobs:
  build-and-push:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0

      - name: Set up kubeconfig
        shell: powershell
        run: |
         $decoded = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.KUBECONFIG_DATA }}"))
         Set-Content -Path "$env:USERPROFILE\.kube\config" -Value $decoded
 
      - name: Replace image tag in manifests
        shell: powershell
        run: |
          (Get-Content k8s/deplyoment.yml) -replace 'harsha12101503/wisecow:latest', "${{ env.IMAGE }}:${{ github.sha }}" | Set-Content k8s/deplyoment.yml
      - name: Ensure Minikube context
        shell: powershell
        run: |
          minikube update-context
          kubectl config use-context minikube
          kubectl cluster-info


      - name: Apply Kubernetes manifests
        shell: powershell
        run: |
          $env:KUBECONFIG="C:\Users\govar\.kube\config"
          kubectl apply -f k8s/
          kubectl rollout status deployment/wisecow
