name: CI/CD for Wisecow

on:
  push:
    branches: [ main ]

env:
  IMAGE: harsha12101503/wisecow

jobs:
  build-and-push:
    runs-on: self-hosted   
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          docker build -t ${{ env.IMAGE }}:latest .
          docker tag ${{ env.IMAGE }}:latest ${{ env.IMAGE }}:${{ github.sha }}
          docker push ${{ env.IMAGE }}:latest
          docker push ${{ env.IMAGE }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted   
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update image tag in manifests
        run: |
          sed -i "s|${{ env.IMAGE }}:latest|${{ env.IMAGE }}:${{ github.sha }}|g" k8s/deployment.yaml

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/wisecow
