name: CI/CD for Wisecow

on:
  push:
    branches: [ main ]

env:
  IMAGE: harsha12101503/wisecow

jobs:
  build-and-push:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Replace image tag in manifests
        run: |
          sed -i "s|harsha12101503/wisecow:latest|${{ env.IMAGE }}:${{ github.sha }}|g" k8s/deplyoment.yml

      - name: Apply Kubernetes manifests
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          kubectl apply -f k8s/
          kubectl rollout status deployment/wisecow
